# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MinhaCalculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MinhaCalculadora(object):
    def setupUi(self, MinhaCalculadora):
        MinhaCalculadora.setObjectName("MinhaCalculadora")
        MinhaCalculadora.setFixedSize(400, 639)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MinhaCalculadora.setWindowIcon(icon)
        self.dividir = QtWidgets.QPushButton(MinhaCalculadora)
        self.dividir.setGeometry(QtCore.QRect(295, 202, 93, 81))
        self.dividir.setStyleSheet("QPushButton#dividir {\n"
"background-color:rgb(255, 232, 147);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.dividir.setObjectName("dividir")
        self.somar = QtWidgets.QPushButton(MinhaCalculadora)
        self.somar.setGeometry(QtCore.QRect(295, 460, 93, 81))
        self.somar.setStyleSheet("QPushButton#somar {\n"
"background-color:rgb(255, 232, 147);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.somar.setObjectName("somar")
        self.p4 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p4.setGeometry(QtCore.QRect(9, 374, 93, 81))
        self.p4.setStyleSheet("QPushButton#p4 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p4.setObjectName("p4")
        self.p8 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p8.setGeometry(QtCore.QRect(104, 288, 94, 81))
        self.p8.setStyleSheet("QPushButton#p8 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p8.setObjectName("p8")
        self.p5 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p5.setGeometry(QtCore.QRect(104, 374, 94, 81))
        self.p5.setStyleSheet("QPushButton#p5 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p5.setObjectName("p5")
        self.visor = QtWidgets.QLabel(MinhaCalculadora)
        self.visor.setGeometry(QtCore.QRect(9, 72, 381, 121))
        self.visor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.visor.setStyleSheet("QLabel#visor {\n"
"font-size: 80px;\n"
"background-color: rgb(230, 230, 230);\n"
"border: 1px solid rgb(158, 158, 158);\n"
"}")
        self.visor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.visor.setIndent(-1)
        self.visor.setObjectName("visor")
        self.subtrair = QtWidgets.QPushButton(MinhaCalculadora)
        self.subtrair.setGeometry(QtCore.QRect(295, 374, 93, 81))
        self.subtrair.setStyleSheet("QPushButton#subtrair {\n"
"background-color:rgb(255, 232, 147);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.subtrair.setObjectName("subtrair")
        self.clear = QtWidgets.QPushButton(MinhaCalculadora)
        self.clear.setEnabled(True)
        self.clear.setGeometry(QtCore.QRect(9, 202, 284, 81))
        self.clear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clear.setAutoFillBackground(False)
        self.clear.setStyleSheet("QPushButton#clear {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.clear.setObjectName("clear")
        self.p9 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p9.setGeometry(QtCore.QRect(200, 288, 93, 81))
        self.p9.setStyleSheet("QPushButton#p9 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p9.setObjectName("p9")
        self.p3 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p3.setGeometry(QtCore.QRect(200, 460, 93, 81))
        self.p3.setStyleSheet("QPushButton#p3 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p3.setObjectName("p3")
        self.p7 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p7.setGeometry(QtCore.QRect(9, 288, 93, 81))
        self.p7.setStyleSheet("QPushButton#p7 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p7.setObjectName("p7")
        self.multiplicar = QtWidgets.QPushButton(MinhaCalculadora)
        self.multiplicar.setGeometry(QtCore.QRect(295, 288, 93, 81))
        self.multiplicar.setStyleSheet("QPushButton#multiplicar {\n"
"background-color:rgb(255, 232, 147);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.multiplicar.setObjectName("multiplicar")
        self.p0 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p0.setGeometry(QtCore.QRect(113, 552, 171, 81))
        self.p0.setStyleSheet("QPushButton#p0 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p0.setObjectName("p0")
        self.p6 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p6.setGeometry(QtCore.QRect(200, 374, 93, 81))
        self.p6.setStyleSheet("QPushButton#p6 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p6.setObjectName("p6")
        self.igual = QtWidgets.QPushButton(MinhaCalculadora)
        self.igual.setGeometry(QtCore.QRect(290, 552, 101, 81))
        self.igual.setStyleSheet("QPushButton#igual {\n"
"background-color:rgb(148, 255, 169);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.igual.setObjectName("igual")
        self.p2 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p2.setGeometry(QtCore.QRect(104, 460, 94, 81))
        self.p2.setStyleSheet("QPushButton#p2 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p2.setObjectName("p2")
        self.p1 = QtWidgets.QPushButton(MinhaCalculadora)
        self.p1.setGeometry(QtCore.QRect(9, 460, 93, 81))
        self.p1.setStyleSheet("QPushButton#p1 {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.p1.setObjectName("p1")
        self.ponto = QtWidgets.QPushButton(MinhaCalculadora)
        self.ponto.setGeometry(QtCore.QRect(12, 552, 91, 81))
        self.ponto.setStyleSheet("QPushButton#ponto {\n"
"background-color:rgb(239, 239, 239);\n"
"font-family: \"Oswald\";\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}")
        self.ponto.setObjectName("ponto")
        self.visor_2 = QtWidgets.QLabel(MinhaCalculadora)
        self.visor_2.setGeometry(QtCore.QRect(9, 10, 381, 71))
        self.visor_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.visor_2.setStyleSheet("QLabel#visor_2 {\n"
"font-size: 40px;\n"
"background-color: rgb(230, 230, 230);\n"
"border: 1px solid rgb(158, 158, 158);\n"
"border-bottom: none;\n"
"}")
        self.visor_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.visor_2.setIndent(-1)
        self.visor_2.setObjectName("visor_2")
        self.dividir.raise_()
        self.somar.raise_()
        self.p4.raise_()
        self.p8.raise_()
        self.p5.raise_()
        self.subtrair.raise_()
        self.clear.raise_()
        self.p9.raise_()
        self.p3.raise_()
        self.p7.raise_()
        self.multiplicar.raise_()
        self.p0.raise_()
        self.p6.raise_()
        self.igual.raise_()
        self.p2.raise_()
        self.p1.raise_()
        self.ponto.raise_()
        self.visor.raise_()
        self.visor_2.raise_()

        self.retranslateUi(MinhaCalculadora)
        QtCore.QMetaObject.connectSlotsByName(MinhaCalculadora)

    def retranslateUi(self, MinhaCalculadora):
        _translate = QtCore.QCoreApplication.translate
        MinhaCalculadora.setWindowTitle(_translate("MinhaCalculadora", "Minha Caculadora"))
        self.dividir.setText(_translate("MinhaCalculadora", "/"))
        self.somar.setText(_translate("MinhaCalculadora", "+"))
        self.p4.setText(_translate("MinhaCalculadora", "4"))
        self.p8.setText(_translate("MinhaCalculadora", "8"))
        self.p5.setText(_translate("MinhaCalculadora", "5"))
        self.visor.setText(_translate("MinhaCalculadora", "0"))
        self.subtrair.setText(_translate("MinhaCalculadora", "-"))
        self.clear.setText(_translate("MinhaCalculadora", "C"))
        self.p9.setText(_translate("MinhaCalculadora", "9"))
        self.p3.setText(_translate("MinhaCalculadora", "3"))
        self.p7.setText(_translate("MinhaCalculadora", "7"))
        self.multiplicar.setText(_translate("MinhaCalculadora", "X"))
        self.p0.setText(_translate("MinhaCalculadora", "0"))
        self.p6.setText(_translate("MinhaCalculadora", "6"))
        self.igual.setText(_translate("MinhaCalculadora", "="))
        self.p2.setText(_translate("MinhaCalculadora", "2"))
        self.p1.setText(_translate("MinhaCalculadora", "1"))
        self.ponto.setText(_translate("MinhaCalculadora", "."))
        self.visor_2.setText(_translate("MinhaCalculadora", "0"))
import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MinhaCalculadora = QtWidgets.QWidget()
    ui = Ui_MinhaCalculadora()
    ui.setupUi(MinhaCalculadora)
    MinhaCalculadora.show()
    sys.exit(app.exec_())
